COPY propertiesraw FROM '/Users/weilu/Scraper/BARKING AND DAGENHAM-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/BARNET-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/BEXLEY-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/BRENT-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/BROMLEY-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/CAMDEN-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/CITY OF LONDON-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/CROYDON-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/EALING-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/ENFIELD-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/GREENWICH-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/HACKNEY-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/HAMMERSMITH AND FULHAM-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/HARINGEY-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/HARROW-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/HAVERING-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/HILLINGDON-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/HOUNSLOW-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/ISLINGTON-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/KENSINGTON AND CHELSEA-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/KINGSTON UPON THAMES-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/LAMBETH-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/LEWISHAM-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/MERTON-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/NEWHAM-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/REDBRIDGE-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/RICHMOND UPON THAMES-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/SOUTHWARK-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/SUTTON-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/TOWER HAMLETS-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/WALTHAM FOREST-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/WANDSWORTH-Properties-2021.csv' DELIMITER ',' CSV HEADER;
COPY propertiesraw FROM '/Users/weilu/Scraper/WESTMINSTER-Properties-2021.csv' DELIMITER ',' CSV HEADER;
